Corrected switch_to_cosmovisor script, completed how-to document for it

diff --git a/deployment/scripts/switch_to_cosmovisor b/deployment/scripts/switch_to_cosmovisor
--- a/deployment/scripts/switch_to_cosmovisor
+++ b/deployment/scripts/switch_to_cosmovisor
@@ -24,7 +24,7 @@ CURR_USER="${USER:-$(whoami 2>/dev/null)}"
 NODE_USER="${CURR_USER:-$DEF_NODE_USER}"
 
 function wait_node_up {
-    local _timeout="${1:-5}"
+    local _timeout="${1:-60}"
     local _try=1
 
     echo -e "Waiting the node becomes up"
@@ -47,7 +47,7 @@ if [[ ! -d "/etc/systemd/system" ]]; then
 fi
 
 if [[ ! -f "./dcld" ]]; then
-    echo "Error. './dcld' file not found"
+    echo "Error. './dcld' file to install not found"
     exit 1
 fi
 
@@ -60,6 +60,15 @@ if [[ ! -f "./cosmovisor.service" ]]; then
     echo "Error. './cosmovisor.service' file not found"
     exit 1
 fi
+
+OLD_DCLD="$(which dcld)"
+
+if [[ -z "$OLD_DCLD" ]]; then
+    echo "Error. No installed 'dcld' found"
+    exit 1
+fi
+
+BIN_DIR="$(dirname "$OLD_DCLD")"
 
 if [[ ! -f "/etc/systemd/system/dcld.service" ]]; then
     echo "Error. '/etc/systemd/system/dcld.service' file not found"
@@ -86,13 +95,13 @@ sudo systemctl disable dcld
 sudo rm -f /etc/systemd/system/dcld.service
 echo "Removed 'dcld' service"
 
-sudo rm -f /usr/bin/dcld
-echo "Removed old stand-alone 'dcld' binary from '/usr/bin/'"
+sudo rm -f "$BIN_DIR"/dcld
+echo "Removed old stand-alone 'dcld' binary from '${BIN_DIR}'"
 
-sudo cp -f ./cosmovisor /usr/bin/
-sudo chown "$NODE_USER" /usr/bin/cosmovisor
-sudo chmod u+x /usr/bin/cosmovisor
-echo "Copied 'cosmovisor' to '/usr/bin/'"
+sudo cp -f ./cosmovisor "$BIN_DIR"/
+sudo chown "$NODE_USER" "$BIN_DIR"/cosmovisor
+sudo chmod u+x "$BIN_DIR"/cosmovisor
+echo "Copied 'cosmovisor' to '${BIN_DIR}'"
 
 mkdir -p "$GENESIS_APP_DIR"
 echo "Created '${GENESIS_APP_DIR}' directory treated by cosmovisor as path to genesis app version"
@@ -126,3 +135,4 @@ echo "Added '${CURRENT_APP_DIR}' to PATH to maintain 'dcld' command associated w
 echo "Execute 'source ~/.profile' or restart shell to take the PATH change effective."
 
 wait_node_up
+echo "Done"
